services:
  jekyll:
    build: .
    container_name: jotspot-jekyll
    network_mode: host
    volumes:
      - .:/srv/jekyll
      - bundle_cache:/usr/local/bundle
    environment:
      - JEKYLL_ENV=development
    command: bundle exec jekyll serve --host 127.0.0.1 --livereload --force_polling

volumes:
  bundle_cache:
